-- ============================================================================
-- 045  Opravy otázek z testu portálu a doplnění pramene a okruhu
-- ============================================================================
--
-- CO CHYBĚLO
-- Test portálu (30. 9. 2026) našel v bance věcné chyby a aplikace bere otázky
-- z tabulky quiz_questions, ne z repozitáře — oprava jen v kódu by se
-- studentům neukázala.
-- • Otázka o „zastavovacím pásu (§ 17)“ tvrdila, že je to donucovací
--   prostředek. Výčet v § 17 odst. 2 zákona č. 555/1992 Sb. ho nemá.
--   Otázka se přepisuje na výčet donucovacích prostředků.
-- • Otázka „Jak přesně zní zákonná výzva…“ vydávala vymyšlenou větu za
--   doslovné znění. Zákon předepisuje jen slova „jménem zákona“.
-- • Vysvětlení k záznamu o použití DP odkazovalo na § 22; správně § 20.
-- • 361 otázek má prázdný pramen a 3 obecný „Banka otázek Supabase“, takže
--   u nich kartičky a banka neukazují číslo zákona. Doplní se z repozitáře.
--
-- CO TENHLE SKRIPT DĚLÁ
-- 1. Přepíše dvě chybné otázky (hledá je podle původního znění; kdo je
--    mezitím upravil, tomu se nepřepíšou).
-- 2. Opraví vysvětlení a pramen u záznamu o použití DP.
-- 3. Doplní pramen a okruh tam, kde chybí. Co lektor vyplnil sám, nemění.
--
-- Skript je idempotentní: druhé spuštění nic nezmění.
-- ============================================================================

BEGIN;

-- 1a. Zastavovací pás → výčet donucovacích prostředků (sp-20)
UPDATE public.quiz_questions
   SET question      = 'Který z uvedených prostředků NENÍ donucovacím prostředkem podle výčtu v § 17 odst. 2 zákona č. 555/1992 Sb.?',
       options       = to_jsonb(ARRAY['prostředek k zamezení prostorové orientace', 'zastavovací pás k zastavení prchajícího auta', 'pouta s poutacím opaskem a předváděcí řetízky', 'vytlačování štítem a vytlačování vozidlem']),
       correct_index = 1,
       explanation   = 'Výčet v § 17 odst. 2 písm. a) až p) je uzavřený a zastavovací pás v něm není. K zastavení vozidla lze z výčtu použít například vytlačování vozidlem (písm. o). Ostatní možnosti výčet obsahuje: pouta s poutacím opaskem (písm. e), předváděcí řetízky (písm. b), vytlačování štítem (písm. n) a prostředek k zamezení prostorové orientace (písm. p). (Právní úprava: § 17 odst. 2 zákona č. 555/1992 Sb.)',
       source        = '§ 17 odst. 2 zákona č. 555/1992 Sb.',
       topic         = 'Výčet donucovacích prostředků'
 WHERE question = 'Za jakých podmínek a jakým způsobem se smí použít donucovací prostředek zastavovací pás (§ 17)?'
   AND NOT EXISTS (SELECT 1 FROM public.quiz_questions WHERE question = 'Který z uvedených prostředků NENÍ donucovacím prostředkem podle výčtu v § 17 odst. 2 zákona č. 555/1992 Sb.?');

-- 1b. „Jménem zákona“ místo vymyšlené doslovné výzvy (va_10)
UPDATE public.quiz_questions
   SET question      = 'Jaká slova musí příslušník podle § 6 odst. 3 písm. b) zákona č. 555/1992 Sb. použít před výzvou k upuštění od protiprávního jednání?',
       options       = to_jsonb(ARRAY['„Jménem zákona“ – další znění výzvy zákon nepředepisuje, příslušník ji formuluje podle situace.', '„Jménem republiky“ – a za nimi celé znění výzvy, které pevně stanoví prováděcí vyhláška.', '„Z moci úřední“ – a za nimi celé znění výzvy, které pevně stanoví nařízení generálního ředitele.', 'Žádná – zákon určitá slova nevyžaduje, stačí srozumitelná výzva s pohrůžkou zákroku.']),
       correct_index = 0,
       explanation   = 'Podle § 6 odst. 3 písm. b) zákona č. 555/1992 Sb. použije příslušník před výzvou slova „jménem zákona“. Doslovné znění celé výzvy zákon nestanoví; příslušník ji formuluje srozumitelně podle situace a do záznamu o použití DP ji uvede tak, jak ji skutečně pronesl. (Právní úprava: § 6 odst. 3 písm. b) z. č. 555/1992 Sb.)',
       source        = '§ 6 odst. 3 písm. b) z. č. 555/1992 Sb.',
       topic         = 'Záznam o použití donucovacích prostředků'
 WHERE question = 'Jak přesně zní zákonná výzva příslušníka před použitím donucovacího prostředku dle § 6 odst. 3 písm. b) zákona č. 555/1992 Sb.?'
   AND NOT EXISTS (SELECT 1 FROM public.quiz_questions WHERE question = 'Jaká slova musí příslušník podle § 6 odst. 3 písm. b) zákona č. 555/1992 Sb. použít před výzvou k upuštění od protiprávního jednání?');

-- 2. Záznam o použití DP: § 20, ne § 22 (va_21)
UPDATE public.quiz_questions
   SET explanation = 'Zákon č. 555/1992 Sb. a navazující metodické listy jasně stanoví povinnost ohlásit a formálně zdokumentovat každé použití DP. Záznam musí obsahovat zákonné náležitosti (důvod, předchozí výzva, výsledek). (Právní úprava: § 20 odst. 1 a 2 zákona č. 555/1992 Sb. a Metodický list č. 5/2014)',
       source      = COALESCE(NULLIF(NULLIF(source, ''), 'Banka otázek Supabase'), '§ 20 odst. 1 zákona č. 555/1992 Sb. a Metodický list č. 5/2014')
 WHERE question = 'Kdo a do jaké lhůty zpracovává „Záznam o použití donucovacího prostředku“ po zákroku proti vězněné osobě?'
   AND explanation LIKE '%§ 22 zákona č. 555/1992 Sb.%';

-- 3. Pramen a okruh z repozitáře tam, kde chybí
UPDATE public.quiz_questions AS q
   SET source = CASE
                  WHEN q.source IS NULL OR btrim(q.source) = '' OR q.source = 'Banka otázek Supabase'
                  THEN COALESCE(v.source, q.source)
                  ELSE q.source
                END,
       topic  = CASE
                  WHEN q.topic IS NULL OR btrim(q.topic) = '' THEN COALESCE(v.topic, q.topic)
                  ELSE q.topic
                END
  FROM (VALUES
  ('Která ústavní práva a svobody jsou občanům ze zákona omezena při výkonu trestu odnětí svobody (VTOS)?', 'Ústavní právo a lidská práva', 'Listina základních práv a svobod (čl. 7, 8, 14, 26, 27) a zákon č. 169/1999 Sb., o VTOS'),
  ('Které vnitrostátní a mezinárodní instituce se zabývají ochranou lidských práv vězněných osob?', 'Ústavní právo a lidská práva', 'Zákon č. 349/1999 Sb., o Veřejném ochránci práv; Úmluva Rady Evropy o zabránění mučení (CPT)'),
  ('Které klíčové mezinárodní právní normy a standardy upravují zacházení s vězněnými osobami?', 'Mezinárodní standardy vězeňství', 'Pravidla Nelsona Mandely OSN (2015), Evropská vězeňská pravidla (2006/2020), Standardy CPT'),
  ('Jak definuje trestní zákoník trestný čin a jak se trestné činy dělí (§ 13 a § 14 TZ)?', 'Trestní právo hmotné', '§ 13 a § 14 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Co jsou podle trestního zákoníku zvlášť závažné zločiny (ZZZ) a jaké jsou typické příklady?', 'Trestní právo hmotné', '§ 14 odst. 3 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Jaká jsou tři vývojová stadia úmyslného trestného činu a jak se charakterizují?', 'Trestní právo hmotné', '§ 20 a § 21 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Jak je v § 20 odst. 1 trestního zákoníku definována příprava trestného činu?', 'Trestní právo hmotné', '§ 20 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Jaká je trestní odpovědnost za pokus a přípravu trestného činu?', 'Trestní právo hmotné', '§ 20 odst. 2, § 21 odst. 2 a § 39 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Jak je posuzována protiprávní činnost dětí do 15 let a mladistvých (15–18 let) podle zákona č. 218/2003 Sb. (ZSM)?', 'Soudnictví ve věcech mládeže', '§ 2, § 5, § 6 a § 93 zákona č. 218/2003 Sb., o soudnictví ve věcech mládeže'),
  ('Které čtyři základní obligatorní (povinné) znaky tvoří skutkovou podstatu trestného činu?', 'Trestní právo hmotné', 'Učební text Právo pro VS ČR (JUDr. A. Rambousek, 2020, s. 36)'),
  ('Co je objektem trestného činu a jak se člení?', 'Trestní právo hmotné', 'Trestní zákoník č. 40/2009 Sb., obecná část'),
  ('Co tvoří objektivní stránku trestného činu a jaké jsou její povinné znaky?', 'Trestní právo hmotné', 'Učební text Právo pro VS ČR (s. 37); § 112 TZ'),
  ('Kdo je subjektem trestného činu a jak se subjekty dělí?', 'Trestní právo hmotné', '§ 22, § 25, § 26 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Jaké jsou formy zavinění v trestním právu a jak se rozlišují (§ 15–19 TZ)?', 'Trestní právo hmotné', '§ 15 až § 19 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Kdo může být pachatelem trestného činu ve smyslu trestního zákoníku (§ 22 TZ)?', 'Trestní právo hmotné', '§ 22 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Kdo je nepřímým pachatelem trestného činu podle § 22 odst. 2 TZ a co je to „živý nástroj“?', 'Trestní právo hmotné', '§ 22 odst. 2 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Jak je v § 23 trestního zákoníku definováno spolupachatelství a co znamená „exces ze spolupachatelství“?', 'Trestní právo hmotné', '§ 23 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Jaké jsou formy trestné součinnosti a účastenství v trestním právu?', 'Trestní právo hmotné', '§ 24, § 364 až § 368 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Co znamená v trestním právu pojem spolčení a srocení?', 'Trestní právo hmotné', '§ 20 odst. 1 zákona č. 40/2009 Sb., trestní zákoník; Učební text Právo, s. 34'),
  ('K jakým okolnostem soud povinně přihlíží při stanovení druhu trestu a jeho výměry (§ 39 TZ)?', 'Trestní právo hmotné', '§ 36 až § 39 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Co znamená v trestním právu pojem společenská škodlivost a princip ultima ratio (§ 12 odst. 2 TZ)?', 'Trestní právo hmotné', '§ 12 odst. 2 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Jaké jsou zákonné hranice výše škody v trestním zákoníku (§ 138 TZ)?', 'Trestní právo hmotné', '§ 138 zákona č. 40/2009 Sb., trestní zákoník (ve znění novely č. 333/2020 Sb.)'),
  ('Kdo je podle § 127 trestního zákoníku úřední osobou a kdy požívá zvýšené trestněprávní ochrany?', 'Trestní právo hmotné', '§ 127 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Jaké jsou základní trestné činy úředních osob podle Hlavy X trestního zákoníku?', 'Trestné činy ve vězeňství', '§ 329 a § 330 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Co je úplatek a jaké trestné činy tvoří úplatkářství dle trestního zákoníku (§ 331–334 TZ)?', 'Trestné činy ve vězeňství', '§ 331 až § 334 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Které zákonné instituty způsobují zánik trestní odpovědnosti pachatele?', 'Trestní právo hmotné', '§ 33 až § 35 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Jaký je rozdíl mezi nepříčetností (§ 26 TZ) a zmenšenou příčetností (§ 27 TZ)?', 'Trestní právo hmotné', '§ 26 a § 27 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Kterých 5 okolností vylučujících protiprávnost taxativně upravuje Hlava III trestního zákoníku?', 'Trestní právo hmotné', '§ 28 až § 32 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Jak je definována krajní nouze v § 28 TZ a jaké jsou její 3 podmínky (meze)?', 'Trestní právo hmotné', '§ 28 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Jak je definována nutná obrana v § 29 TZ a jaké jsou její meze?', 'Trestní právo hmotné', '§ 29 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Za jakých podmínek vylučuje svolení poškozeného protiprávnost (§ 30 TZ) a na co se nevztahuje?', 'Trestní právo hmotné', '§ 30 zákona č. 40/2009 Sb., trestní zákoník; transplantační zákon č. 285/2002 Sb.'),
  ('Jak je v § 31 TZ upraveno přípustné riziko a jaké jsou jeho podmínky?', 'Trestní právo hmotné', '§ 31 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Jak trestní zákoník definuje oprávněné použití zbraně (§ 32 TZ)?', 'Trestní právo hmotné', '§ 32 TZ a § 18–21 zákona č. 555/1992 Sb., o VS a JS ČR'),
  ('Co jsou trestní sankce a jaké druhy trestů upravuje § 52 trestního zákoníku?', 'Trestní právo hmotné', '§ 52 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Co jsou to alternativní tresty a jaké jsou jejich hlavní příklady v českém právu?', 'Trestní právo hmotné', '§ 52, § 60, § 65, § 67 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Kterých 5 druhů ochranných opatření upravuje trestní právo (§ 98–104 TZ a ZSM)?', 'Trestní právo hmotné', '§ 98 až § 104 zákona č. 40/2009 Sb., trestní zákoník'),
  ('Jaký je účel zabezpečovací detence a pro které osoby je určena (§ 100 TZ a z. č. 129/2008 Sb.)?', 'Trestní právo hmotné', '§ 100 zákona č. 40/2009 Sb., TZ a zákon č. 129/2008 Sb., o výkonu zabezpečovací detence'),
  ('Co je hlavním účelem trestního řízení v České republice (§ 1 TrŘ)?', 'Trestní právo procesní', '§ 1 zákona č. 141/1961 Sb., trestní řád'),
  ('Kdo jsou subjekty trestního řízení a jak se liší od stran trestního řízení?', 'Trestní právo procesní', '§ 12 odst. 1 až 6 zákona č. 141/1961 Sb., trestní řád'),
  ('Které tři orgány tvoří taxativní výčet Orgánů činných v trestním řízení (OČTŘ) dle § 12 odst. 1 TrŘ?', 'Trestní právo procesní', '§ 12 odst. 1 a 2 zákona č. 141/1961 Sb., trestní řád'),
  ('Jaké je postavení a role státního zástupce v přípravném řízení a v řízení před soudem?', 'Trestní právo procesní', '§ 174, § 175, § 180 zákona č. 141/1961 Sb., trestní řád'),
  ('Co znamená zásada presumpce neviny a pravidlo „in dubio pro reo“ (§ 2 odst. 2 TrŘ)?', 'Trestní právo procesní', 'Čl. 40 odst. 2 LZPS a § 2 odst. 2 zákona č. 141/1961 Sb., trestní řád'),
  ('Kterých 5 po sobě jdoucích stádií tvoří trestní řízení v ČR?', 'Trestní právo procesní', 'Zákon č. 141/1961 Sb., trestní řád (Části I–V)'),
  ('O kterých závažných zásazích do základních práv a svobod rozhoduje výhradně soudce v přípravném řízení na návrh státního zástupce?', 'Trestní právo procesní', '§ 68, § 69, § 83, § 88, § 116 zákona č. 141/1961 Sb., trestní řád'),
  ('Jaké jsou 3 zákonné důvody vazby stanovené v § 67 trestního řádu?', 'Trestní právo procesní', '§ 67 zákona č. 141/1961 Sb., trestní řád'),
  ('Kdy musí být obviněný propuštěn z vazby a jakými opatřeními lze vazbu nahradit (§ 73, § 73a TrŘ)?', 'Trestní právo procesní', '§ 71, § 72, § 73, § 73a zákona č. 141/1961 Sb., trestní řád'),
  ('Jak se dělí opravné prostředky v trestním řízení a jaké mají účinky?', 'Trestní právo procesní', 'Část III hlava 16 až 21 zákona č. 141/1961 Sb., trestní řád'),
  ('Co je to odpor v trestním řízení a jaké má právní důsledky (§ 314g TrŘ)?', 'Trestní právo procesní', '§ 314g zákona č. 141/1961 Sb., trestní řád'),
  ('Kdy a za jakých podmínek lze povolit obnovu pravomocně skončeného trestního řízení (§ 277 TrŘ)?', 'Trestní právo procesní', '§ 277 až § 289 zákona č. 141/1961 Sb., trestní řád'),
  ('Která tři základní práva představují podle Evropského výboru pro zabránění mučení (CPT) klíčové záruky proti špatnému zacházení od samého počátku zbavení svobody policií?', 'Mezinárodní standardy vězeňství', 'Standardy CPT (Zpráva CPT/Inf (92) 3, body 36–43; CPT/Inf (2002) 15)'),
  ('Jaký je hlavní cíl činnosti Probační a mediační služby (PMS) podle zákona č. 257/2000 Sb. a v jaké fázi se podílí na trestním řízení?', 'Probační a mediační služba', 'Zákon č. 257/2000 Sb., o Probační a mediační službě'),
  ('Jak se z hlediska výkonu člení nepodmíněné tresty odnětí svobody (§ 56 TZ a ZVTOS)?', 'Trestní právo hmotné', '§ 56 zákona č. 40/2009 Sb., trestní zákoník a § 39a zákona č. 169/1999 Sb.'),
  ('Co se v trestním právu procesním rozumí pod pojmem „odklony“ a jaké jsou hlavní příklady?', 'Trestní právo procesní', '§ 307, § 309 zákona č. 141/1961 Sb., trestní řád'),
  ('Za jakých podmínek může policie nebo občan zadržet osobu podezřelou ze spáchání trestného činu a jaké jsou následné lhůty (§ 76 TrŘ)?', 'Trestní právo procesní', '§ 76 zákona č. 141/1961 Sb., trestní řád'),
  ('Jaký je hlavní rozdíl mezi trestným činem (přečinem/zločinem) a přestupkem?', 'Základy práva', 'Zákon č. 250/2016 Sb. a Zákon č. 40/2009 Sb.'),
  ('Který orgán je oprávněn rozhodovat o vzetí obviněného do vazby (§ 68 trestního řádu)?', 'Trestní právo procesní', '§ 68 zákona č. 141/1961 Sb., trestní řád'),
  ('Jaký je opravný prostředek proti rozhodnutí ředitele věznice ve věcech služebního poměru (§ 190 zákona č. 361/2003 Sb.)?', 'Správní řízení a zákon o VS ČR', '§ 190 zákona č. 361/2003 Sb., o služebním poměru příslušníků bezpečnostních sborů'),
  ('Jaké jsou hlavní povinnosti a zákazy pro strážného u hlavního vchodu do věznice?', 'Strážní služba u vchodu', 'NGŘ č. 33/2019 a NGŘ č. 2/2026'),
  ('Jaká je četnost a charakteristika dílčích a technických prohlídek ve věznici?', 'Prohlídky', 'Směrnice pro provádění prohlídek ve věznicích a vazebních věznicích VS ČR'),
  ('Jaký je postup příslušníka Justiční stráže při převzetí střelné zbraně do úschovy od veřejnosti u vstupu do budovy soudu?', 'Justiční stráž', 'Instrukce Ministerstva spravedlnosti č. 8/2022 o Justiční stráži'),
  ('Jaký je rozdíl mezi doručováním písemností soudu typu I (zelený pruh) a typu II (červený pruh)?', 'Justiční stráž – doručování', 'Zákon č. 99/1963 Sb., občanský soudní řád (OSŘ) a kancelářský řád'),
  ('Jaký je stanovený postup strážného na strážní věži, pokud odsouzený vnikne do vnitřního zakázaného pásma a překonává ohradní zeď?', 'Strážní služba – strážní věž', '§ 18 a § 20 zákona č. 555/1992 Sb. a NGŘ č. 33/2019'),
  ('Jaká bezpečnostní pravidla platí pro eskortu vězněné osoby při vyšetření na magnetické rezonanci (MR) v civilní nemocnici?', 'Zdravotní eskorta', 'Metodika eskortní činnosti do zdravotnických zařízení, NGŘ č. 23/2021'),
  ('Jaký je hmotnostní limit pro balíček s potravinami a věcmi osobní potřeby zasílaný vězněné osobě a jak se provádí jeho kontrola?', 'Kontrola balíčků', '§ 24 zákona č. 169/1999 Sb. a Řád výkonu trestu'),
  ('Kdo a za jakých podmínek smí provádět důkladnou osobní prohlídku vězněné osoby spojenou se svlečením?', 'Důkladná osobní prohlídka', '§ 11 zákona č. 555/1992 Sb. a Směrnice pro provádění prohlídek'),
  ('Jaký je bezprostřední postup dozorce při nálezu oběšeného odsouzeného na okenní mříži v cele?', 'Dozorčí služba – mimořádná událost', 'Metodika řešení mimořádných událostí ve věznicích VS ČR'),
  ('Jak postupuje dozorce na vnějším nestřeženém pracovišti při zjištění svévolného odchodu odsouzeného?', 'Nestřežené pracoviště', 'NGŘ č. 33/2019 a metodický pokyn pro dozorčí službu'),
  ('Jaké úkony provádí strážný při kontrole nákladního vozidla vyjíždějícího ze střeženého objektu věznice?', 'Kontrola vozidel', 'NGŘ č. 33/2019 o strážní službě'),
  ('Co znamená zkratka PPZZ a v jakých situacích ji příslušník VS ČR aplikuje?', 'Strážní služba – převzetí stanoviště', 'NGŘ č. 33/2019, o Vězeňské a justiční stráži'),
  ('Jaká oprávnění má příslušník Justiční stráže v jednací síni soudu během hlavního líčení?', 'Justiční stráž – jednací síň', '§ 3 zákona č. 555/1992 Sb. a Instrukce MS ČR č. 8/2022'),
  ('Jakým způsobem a v jakých intervalech se provádí sčítací prověrka vězněných osob na ubytovně?', 'Dozorčí služba – sčítací prověrka', 'Řád výkonu trestu odnětí svobody a NGŘ č. 33/2019'),
  ('Jaký je minimální počet příslušníků eskortní hlídky při předvádění nebezpečné vězněné osoby do civilního zdravotnického zařízení?', 'Eskortní služba – eskorta do nemocnice', 'NGŘ č. 33/2019 o eskortní službě'),
  ('Které předměty jsou striktně zakázány vnášet do střeženého objektu věznice nepovolaným osobám?', 'Zakázané předměty', '§ 28 zákona č. 169/1999 Sb. a NGŘ č. 2/2026'),
  ('Jak reaguje operační středisko (OS) při aktivaci perimetrického čidla v zakázaném pásmu věznice?', 'Strážní služba – signálně bezpečnostní technika', 'Směrnice pro obsluhu SBT a činnost operačních středisek VS ČR'),
  ('K jakým účelům se ve Vězeňské službě ČR využívají služební psi a jak se dělí podle specializace?', 'Kynologie VS ČR', 'NGŘ č. 14/2020 o kynologii VS ČR'),
  ('Jaká jsou pravidla dozoru během přímého kontaktu vězněné osoby s návštěvou v návštěvní místnosti?', 'Návštěvní místnost', '§ 19 zákona č. 169/1999 Sb. a Řád VTOS'),
  ('V jakých případech je velitel eskorty povinen nařídit použití pout a poutacích řemenů (kombinované poutání)?', 'Eskortní služba – poutací technika', '§ 17 zákona č. 555/1992 Sb. a NGŘ č. 33/2019'),
  ('Jaký je prvotní postup dozorce při zjištění kouře a požáru na ubytovně vězněných osob?', 'Mimořádné události – požár', 'Požární poplachová směrnice VS ČR'),
  ('K jakému účelu slouží ve Vězeňské službě ČR detektor nelineárních přechodů (NLJD)?', 'Technické vyhledávací prostředky', 'Metodika bezpečnostně technických prostředků VS ČR'),
  ('Jaká jsou přísná zákonná a metodická pravidla pro provádění důkladné osobní prohlídky (se svlečením do naha)?', 'Metodika bezpečnostních prohlídek', '§ 9 zákona č. 555/1992 Sb. a NGŘ o bezpečnostních prohlídkách'),
  ('Co v praxi VS ČR znamená označení eskortní karty vězněné osoby červeným pruhem?', 'Eskortní služba a rizikové osoby', 'Eskortní řád VS ČR (NGŘ č. 24/2018)'),
  ('Co znamená "zásada dvojic" při výkonu služby ve věznici?', 'Zásady bezpečnosti', 'NGŘ č. 33/2019, o strážní, dozorčí a eskortní službě'),
  ('Jaké jsou bezprostřední povinnosti dozorce po převzetí služby na ubytovně?', 'Dozorčí služba', 'NGŘ č. 33/2019, o strážní, dozorčí a eskortní službě'),
  ('Jaká jsou základní pravidla pro propustkový režim do střeženého objektu?', 'Strážní služba u vchodu', 'NGŘ č. 2/2026, o pravidlech vstupu a vjezdu do objektů VS ČR'),
  ('Je příslušník VS ČR oprávněn použít střelnou zbraň proti davu, pokud z něj vychází nebezpečí?', 'Strážní služba', 'Zákon č. 555/1992 Sb., o VS a JS ČR'),
  ('Jaké jsou povinnosti příslušníka před použitím donucovacího prostředku?', 'Donucovací prostředky', '§ 6 odst. 3 a § 17 zákona č. 555/1992 Sb., o VS a JS ČR'),
  ('Jaké jsou povinnosti velitele eskorty při přepravě vězněných osob k soudnímu jednání?', 'Eskortní služba', 'NGŘ č. 33/2019, o strážní, dozorčí a eskortní službě'),
  ('Co je účelem a základním principem bezpečnostního propusťového systému (komory) při vjezdu vozidel do věznice?', 'Technická ochrana a režim věznice', 'NGŘ č. 2/2026, o pravidlech vstupu a vjezdu do objektů VS ČR'),
  ('Jaké jsou důvody vazby a která právní norma je stanovuje?', 'Výkon vazby – Důvody vazby', '§ 67 zákona č. 141/1961 Sb. (trestní řád) a Studijní text Penologie ZOP A str. 9'),
  ('Jaké jsou hlavní zásady výkonu vazby dle zákona č. 293/1993 Sb.?', 'Zásady výkonu vazby', '§ 2 zákona č. 293/1993 Sb., o výkonu vazby a Studijní text Penologie ZOP A str. 9'),
  ('Jaké jsou hlavní zásady výkonu trestu odnětí svobody (VTOS) dle zákona č. 169/1999 Sb.?', 'Zásady výkonu trestu odnětí svobody', '§ 1 a § 2 zákona č. 169/1999 Sb., o VTOS a Studijní text Penologie ZOP A str. 13'),
  ('Které orgány a na čí návrh rozhodují o uvalení vazby a o propuštění z vazby?', 'Rozhodování o vazbě', '§ 6 zákona č. 293/1993 Sb. a Studijní text Penologie ZOP A str. 9-10'),
  ('Jaký bude postup zaměstnanců VS ČR při přijetí osob do VV, resp. do VTOS?', 'Postup při příjmu do VV a VTOS', '§ 5–8 ZVV, § 6 ZVTOS, vyhlášky 109/1994 a 345/1999 Sb. a Studijní text str. 10, 14'),
  ('Jaké jsou základní úkoly dozorců oddělení výkonu vazby (OVV)?', 'Úkoly dozorců OVV', 'NGŘ č. 2/2022 čl. 3.6 a § 28–32 a Studijní text str. 30'),
  ('Jaké jsou základní úkoly dozorců oddělení výkonu trestu (OVT) v ubytovně odsouzených?', 'Úkoly dozorců OVT v ubytovně', 'NGŘ č. 2/2022 čl. 3.8 a § 68 a Studijní text str. 32–33'),
  ('Jaké rozlišujeme druhy dozorčích stanovišť? Doplňte i vhodnými příklady!', 'Dozorčí stanoviště – Druhy', '§ 103 odst. 2 NGŘ č. 2/2022 a Studijní text str. 27'),
  ('Uveďte, jakými způsoby lze realizovat návštěvy odsouzených!', 'Způsoby realizace návštěv odsouzených', '§ 19 ZVTOS, § 26–28 vyhl. 345/1999 Sb. a Studijní text str. 63–65'),
  ('Uveďte základní povinnosti odsouzených dle § 28 zákona č. 169/1999 Sb.!', 'Základní povinnosti odsouzených', '§ 28 odst. 1 a 2 zákona č. 169/1999 Sb. a Studijní text str. 39–41'),
  ('Co je odsouzeným zakázáno dle § 28 odst. 3 ZVTOS?', 'Zákazy pro odsouzené', '§ 28 odst. 3 zákona č. 169/1999 Sb. a Studijní text str. 44–45'),
  ('Které kázeňské tresty se vykonávají v uzavřeném oddělení během VTOS?', 'Kázeňské tresty v uzavřeném oddílu', '§ 46 ZVTOS, § 63–65 vyhl. 345/1999 Sb. a Studijní text str. 55–56'),
  ('Kteří zaměstnanci VS ČR mají kázeňskou pravomoc ve VV a kteří ve VTOS?', 'Kázeňská pravomoc ve VV a VTOS', 'NGŘ č. 41/2024 § 2–4, Přílohy 1a–1c a Studijní text str. 50–53'),
  ('Jaký je postup zaměstnanců VS ČR při kontrole balíku?', 'Kontrola balíčků a nepovolené předměty', '§ 33 vyhl. č. 345/1999 Sb. a Studijní text str. 68–69'),
  ('Jaké rozlišujeme způsoby (systémy) ubytování vězňů, vysvětlete rozdíly mezi nimi!', 'Způsoby (systémy) ubytování vězňů', '§ 17 vyhl. 345/1999 Sb., § 15 vyhl. 109/1994 Sb. a Studijní text str. 11, 58–59'),
  ('Vyjmenujte rizikové skupiny osob podle NGŘ č. 24/2022 včetně stanovených úředních zkratek!', 'Rizikové vytypované osoby dle NGŘ č. 24/2022', 'NGŘ č. 24/2022 § 3–9 a Studijní text str. 87–88'),
  ('Jaké jsou základní povinnosti dozorce v uzavřeném oddělení?', 'Povinnosti dozorce v uzavřeném oddílu', 'NGŘ č. 2/2022 § 3.12, § 70 a Studijní text str. 35, 54'),
  ('Které kázeňské tresty a v jakém rozsahu se vykonávají v uzavřeném oddělení?', 'Kázeňské tresty a rozsah v uzavřeném oddílu', '§ 46, 64 ZVTOS, § 22, 26 ZVV a Studijní text str. 49, 50, 52'),
  ('Uveďte nejdůležitější režimová omezení v uzavřeném oddělení!', 'Režimová omezení v uzavřeném oddílu', '§ 49 ZVTOS, § 64–65 vyhl. 345/1999 Sb. a Studijní text str. 55–56'),
  ('Jaké rozlišujeme druhy pracovišť odsouzených z hlediska jejich zabezpečení (střežení)?', 'Druhy pracovišť odsouzených', '§ 51–55 vyhl. 345/1999 Sb. a Studijní text str. 79–80'),
  ('Uveďte základní povinnosti dozorce na vnějším nestřeženém pracovišti!', 'Povinnosti dozorce na nestřeženém pracovišti', '§ 67 NGŘ č. 2/2022 a Studijní text str. 34, 52'),
  ('Jaké jsou zákonné důvody propuštění odsouzeného z VTOS?', 'Důvody propuštění z VTOS', '§ 73a zákona č. 169/1999 Sb. a Studijní text str. 89'),
  ('Uveďte nejdůležitější pravomoci dozorového státního zástupce při kontrole podmínek ve VV a VTOS!', 'Pravomoci dozorového státního zástupce', '§ 78 ZVTOS, § 29 ZVV, § 40 ZVD a Studijní text str. 92'),
  ('Uveďte základní způsoby realizace návštěv blízkých osob u odsouzených!', 'Návštěvy blízkých osob – pravidla', '§ 19 zákona č. 169/1999 Sb., § 26 vyhl. 345/1999 Sb. a Studijní text str. 63'),
  ('Uveďte několik příkladů tzv. nedovolených předmětů, které nebudou odsouzeným vydány z doručeného balíku, vysvětlete pojem potravina podléhající rychlé zkáze a doplňte ho příkladem.', 'Potraviny podléhající rychlé zkáze v balíčku', '§ 33 odst. 1 vyhlášky č. 345/1999 Sb. a Studijní text str. 44, 68'),
  ('Jakými způsoby VS ČR zajišťuje zdravotní péči o vězněné osoby?', 'Zajištění zdravotní péče ve VS ČR', '§ 16 ZVTOS, § 18 ZVV, § 23 vyhl. 345/1999 Sb. a Studijní text str. 60'),
  ('Jaký bude postup zaměstnance VS ČR při zjištění stop násilí na těle odsouzeného (obviněného)?', 'Postup při zjištění stop násilí', '§ 20 NGŘ č. 24/2022 a Studijní text str. 88'),
  ('Uveďte 4 příklady institucí (osob), na něž se může obrátit se stížností vězněná osoba v případě, že se domnívá, že byla porušena její zákonem garantovaná práva, či poškozena lidská důstojnost?', 'Instituce pro stížnosti vězněných osob', '§ 26 ZVTOS, § 34 vyhl. 345/1999 Sb. a Studijní text str. 70'),
  ('Uveďte název klíčového mezinárodního dokumentu, který stanovuje podmínky výkonu vězeňství v ČR, současně uveďte i název mezinárodní instituce provádějící monitoring vězeňství a dodržování lidských práv v jednotlivých evropských zemích.', 'Mezinárodní dokumenty a instituce v penologii', 'Evropská vězeňská pravidla, Mandát CPT a Studijní text str. 56, 92'),
  ('Jaká pravidla, či omezení platí při nakládání s korespondencí vězněných osob?', 'Pravidla pro korespondenci vězňů', '§ 17 ZVTOS, § 13 ZVV a Studijní text str. 61–62, 73'),
  ('Která ústavní práva a svobody jsou omezeny ve VTOS?', 'Omezená ústavní práva ve VTOS', '§ 27 zákona č. 169/1999 Sb. a Studijní text str. 71–72'),
  ('Kolik osob se může zúčastnit návštěvy obviněného, jak často se návštěvy realizují?', 'Návštěvy obviněných ve vazbě', '§ 14 odst. 1 zákona č. 293/1993 Sb. a Studijní text str. 73'),
  ('Uveďte povinnosti dozorce v oddělení VV!', 'Dozorčí služba – OVV povinnosti', 'NGŘ č. 2/2022 § 3.6, § 31–32 a Studijní text str. 30'),
  ('Jaké jsou zákonné důvody pro propuštění z VV, kdo o něm rozhoduje?', 'Propuštění z vazby – Důvody a orgány', '§ 6 zákona č. 293/1993 Sb., o výkonu vazby a Studijní text str. 9, 10'),
  ('Co je program zacházení, kdo ho zpracovává a v čem spočívá jeho význam?', 'Program zacházení – Význam a struktura', '§ 40, 41 ZVTOS, § 36 vyhl. 345/1999 Sb. a Studijní text str. 17–19'),
  ('Uveďte několik příkladů činností stanovených v časovém rozvrhu dne, která vnitřní norma jej stanovuje?', 'Časový rozvrh dne (ČRD)', '§ 14 ZVTOS, § 3 vyhl. 109/1994 Sb. a Studijní text str. 19, 41'),
  ('Jak často má obviněný nárok na balíček a kolik osob se může zúčastnit návštěvy?', 'Balíček a návštěvy u obviněného', '§ 14 a § 17 zákona č. 293/1993 Sb. a Studijní text str. 73–74'),
  ('Za jakých okolností může být provedena návštěva u obviněného, který je ve VV z koluzních důvodů (§ 67 písm. b TrŘ)?', 'Koluzní vazba a realizace návštěv', '§ 14 odst. 2 ZVV, § 44 odst. 5 vyhl. 109/1994 Sb. a Studijní text str. 73'),
  ('Vysvětlete, jak je naplňováno právo odsouzeného na korespondenci a jaká jsou jeho případná omezení:', 'Právo odsouzeného na korespondenci a omezení', '§ 18 zákona č. 169/1999 Sb. a Studijní text str. 61–62'),
  ('Jak často má odsouzený nárok na nákup potravin a věcí osobní potřeby, jaká částka je na tyto nákupy uvolňována a dle čeho se určuje její výše?', 'Nákupy potravin a uvolňování financí', '§ 23 ZVTOS, § 31 vyhl. 345/1999 Sb. a Studijní text str. 67–68'),
  ('Jak často a do jaké váhy může přijmout odsouzený balík s potravinami a osobními věcmi, kdo povoluje jeho přijetí?', 'Nárokový balíček – interval a povolení', '§ 24 a § 62 zákona č. 169/1999 Sb. a Studijní text str. 68–69, 84'),
  ('Vyjmenujte a popište základní vybavení cel a ložnic, jak je legislativně upraven počet ubytovaných v cele (ložnici)?', 'Vybavení cel a ubytovací normy', '§ 17 vyhl. 345/1999 Sb., § 15 vyhl. 109/1994 Sb. a Studijní text str. 11, 58–59'),
  ('Za jakých podmínek je umožněno obviněným používání civilního oděvu ve výkonu vazby?', 'Civilní oděv ve výkonu vazby', '§ 12 ZVV, § 29 vyhl. 109/1994 Sb. a Studijní text str. 73'),
  ('Uveďte několik rozdílů v základních právech mladistvých ve výkonu trestního opatření ve srovnání s dospělými ve VTOS:', 'Specifika a práva mladistvých ve VTOS', '§ 60–65 zákona č. 169/1999 Sb. a Studijní text str. 83–84'),
  ('Jaká jsou specifika výkonu zabezpečovací detence a kdo ji zajišťuje?', 'Zabezpečovací detence', 'Zákon č. 129/2008 Sb., o výkonu zabezpečovací detence'),
  ('Jaké jsou dva základní typy věznic v ČR pro výkon trestu odnětí svobody plnoletých pachatelů podle platného znění TZ (§ 56)?', 'Diferenciace věznic', '§ 56 zákona č. 40/2009 Sb., trestní zákoník'),
  ('K čemu slouží v penitenciární praxi nástroj SARPO (Souhrnná analýza rizik a kriminogenních potřeb)?', 'Penitenciární diagnostika', 'Metodika SARPO a koncepce vězeňství ČR'),
  ('Z jakých základních typů aktivit se skládá Program zacházení odsouzeného?', 'Program zacházení', 'Zákon č. 169/1999 Sb., o VTOS a Řád výkonu trestu'),
  ('Která kategorie vězněných osob se označuje zkratkou DVO a jaká platí pro ni specifika?', 'Prevence násilí', 'NGŘ č. 24/2022, o předcházení násilí mezi vězněnými osobami'),
  ('Kdo a na jakém základě rozhoduje o zařazení odsouzeného do konkrétního stupně zabezpečení v rámci věznice s ostrahou?', 'Diferenciace výkonu trestu', '§ 9a zákona č. 169/1999 Sb., o výkonu trestu odnětí svobody'),
  ('Jak často se standardně provádí komplexní hodnocení plnění individuálního programu zacházení u odsouzeného ve VTOS?', 'Program zacházení odsouzených', '§ 40 vyhlášky MS ČR č. 345/1999 Sb., řád výkonu trestu odnětí svobody'),
  ('Jaké jsou zákonné podmínky pro použití donucovacích prostředků (DP) dle § 17 zákona č. 555/1992 Sb.?', 'Použití donucovacích prostředků', '§ 17 odst. 1 a 3 zákona č. 555/1992 Sb., o VS a JS ČR'),
  ('V jakých 5 taxativních případech je příslušník VS ČR oprávněn použít střelnou zbraň dle § 18 odst. 1 zákona č. 555/1992 Sb.?', 'Použití střelné zbraně', '§ 18 odst. 1 zákona č. 555/1992 Sb., o VS a JS ČR'),
  ('Které donucovací prostředky jsou taxativně vyjmenovány v § 17 zákona č. 555/1992 Sb.?', 'Katalog donucovacích prostředků', '§ 17 zákona č. 555/1992 Sb., o VS a JS ČR'),
  ('Vůči kterým osobám je příslušník povinen omezit použití DP a zbraně dle § 19 zákona č. 555/1992 Sb.?', 'Zákonná omezení použití DP a zbraně', '§ 19 zákona č. 555/1992 Sb., o VS a JS ČR'),
  ('Jaký je stanovený postup bezpečné kontroly zbraně (vybití zbraně) u lapače střel?', 'Střelecká příprava – Pistole CZ 75 B / P-10 C', '§ 19 NGŘ č. 33/2019 a střelecký řád VS ČR'),
  ('Jaká je ráže a základní režimy střelby samopalu CZ Scorpion EVO 3A1 používaného u VS ČR?', 'Střelecká příprava – CZ Scorpion EVO 3A1', 'Technický manuál a střelecký řád VS ČR'),
  ('Jaké povinnosti má příslušník VS ČR bezprostředně po použití donucovacích prostředků nebo zbraně dle § 20 zákona č. 555/1992 Sb.?', 'Povinnosti po použití zbraně a DP', '§ 20 zákona č. 555/1992 Sb., o VS a JS ČR'),
  ('Jaká jsou bezpečnostní pravidla a omezení při použití elektrického paralyzéru (Taser / kontaktní paralyzér)?', 'Elektrický paralyzér', 'Metodika použití donucovacích prostředků – elektrošokové zbraně VS ČR'),
  ('Jaká jsou základní taktická pravidla při vstupu hlídky do cely k provedení zákroku proti ozbrojenému agresivnímu odsouzenému?', 'Taktika služebního zákroku v cele', 'Metodika služebních zákroků v uzavřených prostorách, Akademie VS ČR'),
  ('Jaké jsou zásady správného nasazení služebních pout na ruce osoby za zády?', 'Použití pout a poutacích pásů', 'Metodika použití donucovacích prostředků – Poutací technika VS ČR (Kupec)'),
  ('Jaký je okamžitý střelecký drill při selhání výstřelu (tzv. zádržka zbraně / Tap-Rack-Bang)?', 'Střelecká příprava – Závady na zbrani', 'Předpis pro střeleckou přípravu a taktiku VS ČR'),
  ('Jaká látka a typ trysky se standardně využívá u služebních obranných sprejů ve výzbroji VS ČR a jak se aplikují?', 'Slzotvorné a dráždivé prostředky', 'Metodika použití donucovacích prostředků VS ČR'),
  ('Které části těla jsou zakázanými zónami pro údery služebním obuškem při vedení zákroku?', 'Služební obušek a tonfa', 'Metodika použití obušku a taktiky sebeobrany Akademie VS ČR'),
  ('Který z uvedených prostředků NENÍ donucovacím prostředkem podle výčtu v § 17 odst. 2 zákona č. 555/1992 Sb.?', 'Výčet donucovacích prostředků', '§ 17 odst. 2 zákona č. 555/1992 Sb.'),
  ('Jak se provádí první pomoc při podezření na zlomeninu dlouhé kosti končetiny?', 'První pomoc – Zlomeniny a imobilizace', 'Výukové standardy první pomoci Akademie VS ČR'),
  ('Jaký je rozdíl mezi taktickým přebitím (přebití s uschováním) a nouzovým přebitím zbraně?', 'Střelecká příprava – Taktické přebití zbraně', 'Předpis střelecké přípravy a taktiky VS ČR'),
  ('Kdy příslušník VS ČR NENÍ povinen provést služební zákrok dle § 7 odst. 2 zákona č. 555/1992 Sb.?', 'Povinnost zakročit – Výjimky ze zákroku', '§ 7 odst. 2 zákona č. 555/1992 Sb.'),
  ('Jakými způsoby prokazuje příslušník svoji příslušnost k Vězeňské službě ČR (§ 8 zákona č. 555/1992 Sb.)?', 'Prokazování příslušnosti k VS ČR', '§ 8 zákona č. 555/1992 Sb. a vyhláška č. 166/2014 Sb.'),
  ('Jaké jsou zákonné podmínky a meze nutné obrany dle § 29 trestního zákoníku (č. 40/2009 Sb.)?', 'Trestní právo – Nutná obrana', '§ 29 zákona č. 40/2009 Sb., trestní zákoník'),
  ('V čem spočívá základní rozdíl mezi nutnou obranou (§ 29 TZ) a krajní nouzí (§ 28 TZ)?', 'Trestní právo – Krajní nouze', '§ 28 a § 29 zákona č. 40/2009 Sb.'),
  ('U kterých ústavních činitelů a funkcionářů se při vstupu do věznice NEPROVÁDÍ kontrola ani prohlídka zavazadla (§ 80 odst. 2 písm. c NGŘ č. 33/2019)?', 'Vstupy do objektů – Výjimky z prohlídek', '§ 80 odst. 2 písm. c) NGŘ č. 33/2019'),
  ('Na jaké doklady mohou osoby vstupovat do střežených objektů VS ČR dle § 103 NGŘ č. 33/2019?', 'Vstupy do objektů – Vstupní doklady', '§ 103–112 NGŘ č. 33/2019'),
  ('Jaký je správný postup strážného na vchodu při kontrole osoby s implantovaným kardiostimulátorem?', 'Technická kontrola osob – Kardiostimulátor', 'Metodika činnosti VS ČR na vchodech a vjezdech 2020'),
  ('Jaké úkony se musí provést před spuštěním detektoru tepové frekvence (Heartbeat detector) u vozidla?', 'Kontrola vozidel – Detektor tepové frekvence', 'Metodika činnosti VS ČR na vchodech a vjezdech 2020'),
  ('Jaká striktní zásada platí pro nesení zavazadla s peněžní hotovostí při přepravě Justiční stráží dle § 144?', 'Justiční stráž – Přeprava cenin a peněz', '§ 144 odst. 6 NGŘ č. 33/2019 a Instrukce MS č. 8/2022'),
  ('Jaké jsou povinnosti příslušníka Justiční stráže při doprovodu soudního vykonavatele k odebrání nezletilého dítěte (§ 143)?', 'Justiční stráž – Asistence při odnětí dítěte', '§ 143 NGŘ č. 33/2019 a Instrukce MS č. 8/2022'),
  ('U kterého typu soudní obálky NIKDY nenastává fikce doručení vhozením do schránky (§ 146 / OSŘ)?', 'Justiční stráž – Doručování písemností a obálky', '§ 146 NGŘ č. 33/2019 a § 49 odst. 5 OSŘ'),
  ('Jaké jsou hodnostní sbory a hodnostní označení ve Vězeňské službě ČR dle zákona č. 361/2003 Sb.?', 'Služební zdvořilost – Hodnosti ve VS ČR', 'Zákon č. 361/2003 Sb. a NGŘ č. 38/2018'),
  ('Ve kterých situacích příslušník VS ČR podle NGŘ č. 38/2018 NEZDRAVÍ a nepodává hlášení?', 'Pořadová příprava – Kdy příslušník nezdraví', 'Čl. 11 NGŘ č. 38/2018 o pravidlech služební zdvořilosti'),
  ('Jaké úkony musí provést velitel eskorty v případě úmrtí eskortované osoby během přepravy (§ 73)?', 'Eskorty – Postup při úmrtí vězně', '§ 73 NGŘ č. 33/2019 a metodika eskort (Kupec)'),
  ('Kdo rozhoduje o zařazení vězněné osoby do kategorie DVO (další vytypovaná osoba) a DVO-P (profese) dle NGŘ č. 24/2022?', 'Prevence násilí – Kategorie vězňů', '§ 8 a § 9 NGŘ č. 24/2022'),
  ('Proč se řetízková i pevná nožní pouta přikládají VÝHRADNĚ na holé nohy nad kotníky a NIKDY přes kalhoty?', 'Metodika poutání – Nožní pouta', 'Metodická příručka poutání ve VS ČR (Kupec)'),
  ('Které části formuláře Záznamu o použití donucovacího prostředku vyplňuje a podepisuje zakročující příslušník (ML č. 5/2014)?', 'Dokumentace – Záznam o použití DP', '§ 4 Metodického listu ředitele odboru VaJS č. 5/2014'),
  ('Ve kterých situacích je příslušník VS ČR oprávněn použít pouta (nebo prostředky k zamezení prostorové orientace) jako donucovací prostředek?', 'Donucovací prostředky', '§ 17 zákona č. 555/1992 Sb., o VS a JS ČR'),
  ('U jakých kategorií osob je příslušníkům VS ČR zakázáno použít úderů, kopů, slzotvorných prostředků, taseru a zbraně (neplatí pro nutnou obranu a krajní nouzi)?', 'Donucovací prostředky', '§ 19 odst. 1 zákona č. 555/1992 Sb., o VS a JS ČR'),
  ('Jak zní první a nejdůležitější pravidlo bezpečné manipulace se střelnou zbraní?', 'Zbraňová bezpečnost', 'Předpis pro střeleckou přípravu a bezpečnost manipulace se zbraněmi'),
  ('Jaké je základní taktické pravidlo při nečekaném útoku nožem na krátkou vzdálenost?', 'Taktická sebeobrana', 'Metodika taktické sebeobrany Akademie VS ČR'),
  ('Jaký je princip účinku elektrického paralyzéru (např. Taser) používaného VS ČR?', 'Donucovací prostředky', '§ 17 zákona č. 555/1992 Sb. a manuál výrobce'),
  ('Který prostor se při manipulaci se střelnou zbraní (vybíjení, nabíjení, rána jistoty) považuje za bezpečný prostor?', 'Střelecká příprava', 'Předpis o střelecké přípravě a zbraňové službě VS ČR'),
  ('Jaká povinnost příslušníka VS ČR předchází použití zbraně podle § 20 zákona č. 555/1992 Sb., je-li to s ohledem na okolnosti možné?', 'Zákonné podmínky užití zbraně', '§ 20 zákona č. 555/1992 Sb., o VS a JS ČR'),
  ('Jaká je ráže, kapacita zásobníku a charakteristika útočné pušky CZ BREN 2 zařazené ve výzbroji VS ČR?', 'Střelecká příprava – Útočná puška CZ BREN 2', 'Technická specifikace výzbroje VS ČR a předpis pro střeleckou přípravu'),
  ('Co zkoumá terminální (cílová) balistika a jaký je hlavní účel celoplášťové střely (FMJ) služebního střeliva 9×19 mm Luger?', 'Balistika a zastavovací účinek', 'Učební texty Akademie VS ČR – Nauka o zbraních a střelivu'),
  ('Ze kterých 4 základních částí se skládá jednotný náboj pro služební pistole a samopaly (např. 9×19 mm Luger)?', 'Konstrukce střeliva', 'Zákon č. 119/2002 Sb., o střelných zbraních a střelivu (příloha – vymezení pojmů)'),
  ('Jaká je správná optická rovina při míření mechanickými mířidly (muška – hledí) a na co musí střelec primárně zaostřit zrak?', 'Mířidla a zamíření', 'Metodika střelecké přípravy Akademie VS ČR'),
  ('Co je to psychologie, jaký má cíl a z jakého vědního oboru se vyvinula?', 'Pojem a historie psychologie', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 3'),
  ('Jaké jsou hlavní skupiny psychických jevů osobnosti?', 'Struktura psychických jevů osobnosti', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 7'),
  ('Jak lze v psychologii chápat pojem osobnost (v širším a užším smyslu)?', 'Pojem osobnost a její pojetí', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 7, 9'),
  ('Co je to biologická determinace a co sociální determinace osobnosti?', 'Determinace osobnosti', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 7, 55'),
  ('Co je to socializace a jaké jsou její 4 hlavní mechanismy?', 'Socializace a její mechanismy', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 11–12'),
  ('Co je to sociální adaptace a jaké 4 techniky člověk volí při směřování k cíli?', 'Sociální adaptace a její techniky', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 13'),
  ('Co je výsledkem dobré socializace a co je výsledkem špatné socializace (maladaptace)?', 'Výsledek socializace a maladaptace', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 12–14'),
  ('Co je to sociální skupina a jaké 4 základní znaky mají všechny skupiny společné?', 'Sociální skupiny a jejich znaky', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 15, 17'),
  ('Jak je charakterizována rodina z hlediska sociální psychologie?', 'Charakteristika rodiny', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 16, 18–19'),
  ('Co je to komunikace a jaké 3 úrovně rozlišujeme u verbální komunikace?', 'Komunikace a její roviny', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 24–25'),
  ('Z čeho se skládá neverbální komunikace a kolik procent celkového procesu komunikace tvoří?', 'Neverbální komunikace', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 24, 26–29'),
  ('Jak působí na komunikaci styčná plocha a jak komunikační bariéra? Uveďte příklady.', 'Styčná plocha a komunikační bariéry', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 25, 62'),
  ('Co je to sociální percepce, k čemu slouží a jaké jsou 3 typické chyby v sociální percepci?', 'Sociální percepce a její chyby', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 19–20'),
  ('Co je to asertivita a jaké známe základní asertivní techniky?', 'Asertivita a asertivní techniky', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 20, 22–23'),
  ('Co je to dav, jaké má 4 základní znaky a jak se dělí?', 'Dav, jeho znaky a klasifikace', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 29–30'),
  ('Jaké role mohou zastávat jednotlivci v davu a koho je nutné izolovat jako prvního?', 'Role jedince v davu', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 30–31'),
  ('Co je to droga a jak se drogy dělí podle účinku a podle původu?', 'Drogy a jejich dělení', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 38, 40, 45'),
  ('Jak se projevuje užití jednotlivých skupin drog na zornicích (zúžení vs. rozšíření)?', 'Projevy užití drog na zornicích', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 41, 42, 43, 44, 45'),
  ('Který způsob aplikace drog je z hlediska aktuálního ohrožení života nejnebezpečnější a proč?', 'Nebezpečí způsobů aplikace drog', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 40, 45'),
  ('Co je to závislost, jak se dělí na fyzickou a psychickou a jak se projevují?', 'Závislost fyzická vs. psychická', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 38–39'),
  ('Co jsou to nelátkové (behaviorální) závislosti a jaké jsou jejich příklady?', 'Nelátkové (behaviorální) závislosti', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 47–48'),
  ('Jaká jsou 4 vývojová stadia alkoholismu (podle Jellineka)?', 'Stadia alkoholismu podle Jellineka', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 46–47'),
  ('Jaké jsou 3 základní vývojové fáze gamblerství a jak se liší gambler od toxikomana?', 'Fáze patologického hráčství (gamblingu)', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 48–49'),
  ('Jaké jsou 4 základní typy náročných životních situací a jaké známe druhy konfliktů?', 'Náročné životní situace', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 35–38'),
  ('Kým a čím se zabývá forenzní psychologie a jak se dělí na další podobory?', 'Forenzní psychologie a její podobory', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 5, 52'),
  ('Jak lze dělit pachatele trestné činnosti z pohledu forenzní psychologie?', 'Typologie pachatele trestných činů', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 52–55'),
  ('Jak se dělí příčiny páchání trestné činnosti (patogenní činitelé vnitřní a vnější)?', 'Příčiny páchání trestné činnosti', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 55–56'),
  ('Jaké jsou 3 nejčastější typy reakcí obviněných na zátěžovou situaci vazby?', 'Reakce obviněných ve výkonu vazby (VV)', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 65–66'),
  ('Jakých 5 typů adaptace na podmínky VTOS vymezil Jiří Čepelák?', 'Způsoby přizpůsobení se VTOS podle Čepeláka', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 57, 67'),
  ('Jakých 5 stádií má typický průběh krize z uvěznění („šok z izolace“)?', 'Průběh krize z uvěznění', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 60–62'),
  ('Co je to šikana a jak se dělí na skrytou a zjevnou v prostředí věznice?', 'Šikana ve vězeňském prostředí', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 70, 74'),
  ('Čím se zabývá penitenciární psychologie a jaká je role vězeňského psychologa?', 'Penitenciární psychologie', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 57, 62'),
  ('Co znamenají pojmy automutilace a suicidium a jaký je mezi nimi zásadní rozdíl?', 'Automutilace a suicidium', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 74–76'),
  ('Jaké mohou být základní způsoby řešení konfliktů a jaký je správný postup řešení?', 'Způsoby řešení konfliktů', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 36–37, 72'),
  ('Které poruchy osobnosti (psychopatie) se mohou nejčastěji projevovat agresivním a násilným chováním?', 'Poruchy osobnosti a agresivita', 'Učební texty předmětu Psychologie, Akademie VS ČR 2023, str. 31–32, 54, 70'),
  ('Co je hlavním cílem verbální deeskalace při jednání s agresivním nebo afektivním vězněm?', 'Krizová komunikace', 'Metodika krizové intervence VS ČR'),
  ('Co se v psychologii rozumí pod pojmem Stockholmský syndrom, který se může vyskytnout například při vzetí rukojmí?', 'Penitenciární psychologie', 'Základy psychologie pro bezpečnostní sbory'),
  ('Která z následujících technik je považována za efektivní součást psychohygieny pro prevenci syndromu vyhoření u příslušníků bezpečnostních sborů?', 'Syndrom vyhoření', 'Psychologie pro výkon služby (Metodika GŘ VS ČR)'),
  ('Jaké jsou nejčastější formy manipulace, kterými se vězni snaží ovlivnit personál (např. k získání výhod nebo zakázaných věcí)?', 'Sociální interakce', 'Penitenciární psychologie'),
  ('Které tři složky tvoří Ringelův presuicidální syndrom (varovné signály před sebevraždou)?', 'Prevence suicidiálního jednání', 'Metodika krizové intervence a prevence sebevražd VS ČR'),
  ('Jaký je bezprostřední postup personálu při zjištění, že vězněná osoba vykazuje akutní suicidiální chování (např. sebepoškozování, příprava smyčky)?', 'Krizová intervence', 'NGŘ č. 19/2016 o prevenci sebevražedného jednání vězněných osob'),
  ('Který komunikační přístup je nejúčinnější při verbální deeskalaci agresivního a rozrušeného vězně?', 'Verbální deeskalace konfliktů', 'Metodika penitenciární komunikace a deeskalace konfliktů'),
  ('Jakými jevy se zabývá vědní disciplína Etika?', 'Základní pojmy etiky', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 1'),
  ('Jaký je vztah svobody a odpovědnosti při rozhodování a jednání člověka?', 'Svoboda a odpovědnost', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 1–3'),
  ('O jaké společné základy se opírají normy mravní, morální a právní?', 'Normativní systémy', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 1–2'),
  ('Jaký vztah k našemu životu má idea a směr jednání, který označujeme jako nejvyšší etický cíl?', 'Etický cíl', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 7'),
  ('Co jsou při rozhodování a jednání člověka sankce vnitřní a vnější, pozitivní a negativní?', 'Sankce v normativních systémech', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 1–2'),
  ('Jaké sankce při rozhodování a jednání člověka využívá normativní systém mravnost?', 'Normativní systém mravnost', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 2'),
  ('Jaké sociální sankce při rozhodování a jednání člověka využívá normativní systém morálka?', 'Normativní systém morálka', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 2'),
  ('Jaké sociální sankce při rozhodování a jednání člověka využívá normativní systém právo?', 'Normativní systém právo', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 2'),
  ('Čím se zabývá etická disciplína „Individuální etika“?', 'Individuální etika', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 3'),
  ('Jaké souvislosti rozlišuje etická disciplína „Deskriptivní etika“?', 'Deskriptivní etika', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 8'),
  ('Co je to právní vědomí?', 'Právní vědomí', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 2'),
  ('Jaký význam pro míru socializace má péče o rozvoj právního vědomí?', 'Právní vědomí a socializace', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 2–4'),
  ('Jaké nároky na právní vědomí jsou kladeny na osoby, na které jsou delegovány kompetence výkonu státní moci (zákonodárné, soudní a výkonné)?', 'Požadavky na nositele státní moci', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 2, 7'),
  ('O které ústavní a další zákony ČR a mezinárodní doporučení se opírá ochrana lidských práv vězněných osob?', 'Prameny ochrany LP', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 2–4'),
  ('Co je to korupce a jaké jsou její formy?', 'Podstata korupce', 'NGŘ č. 28/2018 Příloha 1; Studijní opora str. 12'),
  ('Co obsahuje Katalog korupčních rizik, který je přílohou NGŘ č. 28/2018?', 'Katalog korupčních rizik', 'NGŘ č. 28/2018, Přílohy 2–5'),
  ('Je v Katalogu korupčních rizik uvedeno jednání, při kterém vzniká korupční riziko, nebo trestní sazby za korupci?', 'Katalog korupčních rizik – obsah', 'NGŘ č. 28/2018, § 1 a Přílohy 2–5; Studijní opora str. 12'),
  ('Co vede ke správnému etickému rozhodnutí?', 'Etické rozhodování', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 1, 7'),
  ('Proč se z Etiky na základě vzájemných dohod členů společnosti rodí normativní systém Právo?', 'Vznik práva z etiky', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 2'),
  ('Čím se zabývá etická disciplína Axiologie?', 'Axiologie', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 3'),
  ('Co je to hodnotový žebříček a která disciplína zkoumá jeho vznik a projevy?', 'Hodnotový žebříček', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 3'),
  ('Jaké jsou příčiny deformace hodnotového systému u pachatelů trestné činnosti?', 'Deformace hodnot pachatelů', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 3–4'),
  ('Jak se nazývá etická nauka o povinnostech?', 'Deontologie', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 3, 8'),
  ('Jakým způsobem jsou ve společnosti tvořeny normy?', 'Tvorba norem', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 1–2, 7–8'),
  ('O které mezinárodní konvence se opírá model zacházení s vězni v ČR?', 'Mezinárodní konvence vězeňství', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 4'),
  ('K čemu nám slouží etický cíl a jaký vztah bychom k němu měli zaujmout?', 'Vztah k etickému cíli', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 7'),
  ('Jak se liší právo od etiky?', 'Právo vs. Etika', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 1–2'),
  ('Která etická disciplína rozlišuje vyšší a nižší hodnoty, či hierarchii hodnot podle jejich vztahu k nejvyššímu etickému cíli?', 'Hierarchie hodnot', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 3'),
  ('Čím se zabývá etická disciplína deontologie?', 'Obsah deontologie', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 3, 8'),
  ('O jaké vztahy se opírá normativní etika?', 'Normativní etika', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 1–3'),
  ('Jaký vztah máme zaujmout vůči genderovým stereotypům a předsudkům v podmínkách VS ČR?', 'Genderové stereotypy ve VS ČR', 'Studijní opora str. 9; EVP bod 85; NGŘ 28/2018 Příloha 6 Čl. 4'),
  ('Jak se vyvíjí a jak v praxi působí úroveň právního vědomí členů společnosti?', 'Úroveň právního vědomí', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 2'),
  ('V jakých případech lze omezit rovný přístup k lidským právům a základním svobodám zaručeným ústavními zákony ČR?', 'Meze omezení základních práv', 'Listina základních práv a svobod (č. 2/1993 Sb.) Čl. 4; Studijní opora str. 10'),
  ('Ve kterých evropských městech sídlí nejdůležitější mezinárodní orgány chránící lidská práva vězněných osob?', 'Sídla mezinárodních orgánů LP', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 5'),
  ('Které instituce kontrolující lidská práva vězňů se opírají o vládní dohody a které jsou nevládní organizace (NGO)?', 'Vládní vs. nevládní instituce LP', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 5–6'),
  ('Které z právních norem v právním řádu České republiky mají nejvyšší právní sílu?', 'Právní síla norem ČR', 'Ústava ČR Čl. 1, Čl. 10, Čl. 112; Studijní opora str. 6'),
  ('Ze kterých mezinárodních konvencí a doporučení vyplývá povinnost vzdělávání vězeňského personálu v oblasti péče o lidská práva vězněných osob?', 'Povinnost vzdělávání personálu v LP', 'EVP bod 81.4; Studijní opora str. 3–4'),
  ('Jaká základní doporučení a zásady obsahuje Kodex profesní etiky zaměstnance a příslušníka VS ČR (Příloha č. 6 NGŘ č. 28/2018)?', 'Kodex profesní etiky VS ČR', 'Příloha č. 6 k NGŘ č. 28/2018, Čl. 1–8'),
  ('Jaký význam pro komunikaci s vězni, kolegy i nadřízenými má výcvik podle pravidel služební zdvořilosti a pořadové přípravy ve VS ČR?', 'Služební zdvořilost a komunikace', 'Studijní opora str. 9; NGŘ č. 38/2018'),
  ('Jaký vztah nastává mezi nejvyšším etickým cílem, mravním příkazem „Nezabiješ!“ a § 18 zákona č. 555/1992 Sb. v případě, že příslušník VS ČR použil střelnou zbraň?', 'Etika použití zbraně a imperativ Nezabiješ', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 7–8; § 18 a § 20 z. 555/1992 Sb.'),
  ('Jak se má zachovat příslušník VS ČR, pokud se stane svědkem extremistických projevů vězněných osob, kterým nejsou přítomny další osoby?', 'Extremistické projevy', 'Studijní opora str. 9, 15; NGŘ č. 28/2018 Příloha 6'),
  ('Jak má být genderově a bezpečnostně zajištěn standardní průběh osobních prohlídek občanů a vězněných osob?', 'Osobní prohlídky a gender', 'Studijní opora str. 9; EVP body 54.5–54.7; § 11 odst. 2 z. 555/1992 Sb.'),
  ('Na jakém postupu a principech je založena asertivní komunikace příslušníků VS ČR?', 'Asertivní komunikace', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 9'),
  ('Jaká práva a povinnosti musí být všemi zúčastněnými respektovány, když je příslušník velen na strážní stanoviště se zbraní?', 'Zákonná ochrana na strážním stanovišti', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 9'),
  ('Je účast na duchovní péči pro vězněné osoby povinná?', 'Dobrovolnost duchovní péče', 'Studijní opora str. 10; EVP bod 29.3; Listina Čl. 15, 16'),
  ('Kdo a jakou formou poskytuje vězněným osobám duchovní péči ve věznicích VS ČR?', 'Organizace duchovní péče', 'Studijní opora pro ZOP A – předmět Profesní etika, str. 10'),
  ('Komu lze sdělovat osobní údaje a informace o umístění vězněných osob?', 'Poskytování osobních údajů vězňů', '§ 9, § 23a zákona č. 555/1992 Sb.; NGŘ č. 28/2018'),
  ('Jak se má zachovat příslušník nebo zaměstnanec VS ČR, jestliže se při výběrovém řízení o zakázkách nebo při zacházení s vězněnými osobami setká s osobou v příbuzenském nebo přátelském vztahu?', 'Střet zájmů a podjatost', 'NGŘ č. 28/2018 Příloha 6 Čl. 5, 7; Studijní opora str. 12, 15'),
  ('Jaká je nejvyšší trestní sazba odnětí svobody za korupční jednání (úplatkářství) dle Trestního zákoníku?', 'Trestní sazby za korupci', 'Zákon č. 40/2009 Sb. (trestní zákoník) § 331; Studijní opora str. 12'),
  ('Na úkor koho se obohacují pachatelé korupce?', 'Důsledky korupce pro společnost', 'NGŘ č. 28/2018 Příloha 1 Preambule; Studijní opora str. 12, 15'),
  ('Jaké etické a právní důsledky má ztráta osobní bezúhonnosti pro příslušníka bezpečnostního sboru?', 'Etický kodex', 'Zákon č. 361/2003 Sb. a Kodex profesní etiky VS ČR'),
  ('Co je podle Protikorupčního programu VS ČR základní povinností příslušníka, kterému je nabídnut úplatek?', 'Protikorupční program', 'Protikorupční program VS ČR (NGŘ č. 28/2018)'),
  ('K čemu se vztahuje princip "nulové tolerance" v etickém kodexu vězeňského personálu?', 'Etický kodex', 'Kodex profesní etiky a Evropská úmluva o lidských právech'),
  ('Jak by se měl příslušník VS ČR chovat v době mimo službu (v občanském životě a na sociálních sítích)?', 'Profesní chování', '§ 46 zákona č. 361/2003 Sb. a Kodex profesní etiky VS ČR'),
  ('Co znamená požadavek "nestrannosti" při výkonu služby ve věznici?', 'Základní principy', 'Kodex profesní etiky VS ČR'),
  ('Může příslušník nebo zaměstnanec VS ČR přijmout peněžitý dar nebo pozornost od rodinného příslušníka vězněné osoby jako poděkování za lidský přístup?', 'Střet zájmů a přijímání darů', '§ 46 zákona č. 361/2003 Sb. a Etický kodex VS ČR'),
  ('Která mezinárodní úmluva a evropská pravidla tvoří základní etický standard zacházení s vězněnými osobami v podmínkách VS ČR?', 'Důstojnost a lidská práva', 'Evropská vězeňská pravidla (Doporučení Rec(2006)2) a EÚLP'),
  ('Co je předmětem pedagogiky podle učebních textů?', 'Předmět pedagogiky', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 4'),
  ('Které z následujících patří mezi základní pedagogické principy pro zajištění účinného vzdělávacího procesu?', 'Základní pedagogické principy', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 11'),
  ('Jaké prostředky výchovy na nás mohou výchovně působit (záměrně i mimochodem)?', 'Prostředky výchovy', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 11–12'),
  ('Jak se dělí základní složky výchovy?', 'Složky výchovy', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 11'),
  ('Jaké 4 základní funkce plní rodina v současné společnosti?', 'Funkce rodiny', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 17–18'),
  ('Co je cílem speciální pedagogiky a co znamená pojem integrace v tomto kontextu?', 'Cíle speciální pedagogiky a integrace', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 24, 29'),
  ('Které terapeutické (nápravné) metody využívá speciální pedagogika k nápravě obtíží a zabránění defektivity?', 'Terapeutické (nápravné) metody', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 29–30'),
  ('Jaké jsou typické charakteristiky osobnosti mentálně retardovaného jedince (z psychopedického hlediska)?', 'Osobnost mentálně retardovaného jedince', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 36, 81'),
  ('Jaké jsou současné trendy ve vzdělávání osob se speciálními vzdělávacími potřebami (např. s mentální retardací)?', 'Trendy ve vzdělávání mentálně retardovaných', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 26, 31'),
  ('Jaké zásady by měl personál dodržovat při komunikaci s mentálně retardovaným odsouzeným?', 'Komunikace s mentálně retardovanými', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 35–37, 81'),
  ('Která ze speciálně pedagogických disciplín se primárně zabývá výchovou a vzděláváním osob s poruchami chování?', 'Etopedie - definice', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 25, 41'),
  ('Jak definujeme poruchu chování a co bývá její nejčastější příčinou?', 'Poruchy chování a jejich příčiny', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 41–42'),
  ('Jak se z etopedického hlediska dělí poruchy chování podle jejich společenské škodlivosti?', 'Dělení poruch chování dle škodlivosti', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 50–51'),
  ('Co je to ústavní a ochranná výchova a v jakých zařízeních se realizují?', 'Ústavní a ochranná výchova', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 52–54'),
  ('Která aplikovaná pedagogická disciplína se zaměřuje na výchovu a vzdělávání osob odsouzených k výkonu trestu odnětí svobody?', 'Penitenciární pedagogika - definice', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 65'),
  ('Jaké jsou základní výchovné prostředky, které se využívají k působení na odsouzené v rámci penitenciární pedagogiky?', 'Prostředky penitenciární pedagogiky', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 68'),
  ('Co je to Program zacházení s odsouzeným, jaký je jeho cíl a kdo jej zpracovává?', 'Program zacházení', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 69–70'),
  ('Do jakých pěti hlavních oblastí (aktivit) se člení program zacházení s odsouzenými?', 'Oblasti programu zacházení', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 70'),
  ('Co znamená zkratka SARPO ve vězeňství a jaký je význam tohoto nástroje?', 'Diagnostika SARPO', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 69'),
  ('Jakou výchovnou funkci plní kázeňský trest v penitenciárním prostředí?', 'Kázeňský trest a jeho funkce', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 68'),
  ('Jaké zásady musí personál dodržovat při ukládání kázeňských trestů odsouzeným?', 'Zásady ukládání trestů', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 68'),
  ('Jakou výchovnou funkci plní v penitenciárním prostředí kázeňská pochvala/odměna?', 'Kázeňské odměny a jejich funkce', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 68'),
  ('Kdo má ve věznici pravomoc ukládat odsouzeným kázeňské tresty a odměny?', 'Kázeňská pravomoc', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 68 (implicitní znalost zák. 169/1999 Sb.)'),
  ('Které výchovné funkce plní ve výkonu trestu stanovený ústavní pořádek (režim)?', 'Funkce režimu', 'Učební texty předmětu Pedagogika, Akademie VS ČR, str. 68'),
  ('Čím se zabývá etopedie v rámci speciální pedagogiky?', 'Speciální pedagogika', 'Základy speciální pedagogiky pro bezpečnostní sbory'),
  ('Co jsou v pedagogice metody výchovy?', 'Obecná pedagogika', 'Základy obecné pedagogiky'),
  ('Jaký je rozdíl mezi mentální retardací (oligofrenií) a demencí?', 'Speciální pedagogika', 'Speciální pedagogika - psychopedie'),
  ('Co znamená v pedagogice zásada přiměřenosti (individuálního přístupu)?', 'Didaktické zásady', 'Obecná didaktika'),
  ('Čím se zabývá vědní obor andragogika?', 'Oborové členění', 'Základy andragogiky'),
  ('V čem spočívá princip individuálního přístupu v pedagogickém působení na vězněné osoby?', 'Zásady penitenciární pedagogiky', 'Penitenciární pedagogika a metodika zacházení VS ČR'),
  ('Která kritéria pedagogického hodnocení odsouzeného jsou stěžejní pro podklad soudu k rozhodování o podmíněném propuštění dle § 88 TZ?', 'Hodnocení odsouzených pro soud', '§ 88 trestního zákoníku (zákon č. 40/2009 Sb.) a Metodika hodnocení odsouzených'),
  ('Jaký je prioritní a správný postup při masivním tepenném krvácení z končetiny (např. po bodném poranění odsouzeným)?', 'Zástava masivního krvácení & TCCC', 'TCCC Guidelines & Standardy neodkladné první pomoci Akademie VS ČR'),
  ('Jaký je správný poměr stlačování hrudníku a umělých vdechů při kardiopulmonální resuscitaci (KPR) dospělého člověka podle platných doporučení ERC?', 'Zástava dechu a oběhu – KPR dospělého', 'Doporučené postupy ERC (European Resuscitation Council)'),
  ('Jak se postupuje při použití AED (automatizovaného externího defibrilátoru) umístěného ve věznici u osoby v bezvědomí bez normálního dýchání?', 'Automatizovaný externí defibrilátor (AED)', 'ERC Guidelines – Resuscitation with AED & Metodika VS ČR'),
  ('Jaký je správný postup příslušníka při nálezu oběšené osoby na cele?', 'Pokus o sebevraždu oběšením', 'Metodika řešení mimořádných událostí a suicidálního jednání VS ČR'),
  ('Jak se poskytuje první pomoc při otevřeném (penetrujícím) poranění hrudníku, kdy je slyšet nasávání vzduchu do hrudní dutiny?', 'Otevřené poranění hrudníku (Pneumotorax)', 'TCCC Guidelines & Traumatologie v neodkladné péči'),
  ('Kdy je indikováno uložení postiženého do zotavovací (stabilizované) polohy na boku?', 'Zotavovací (stabilizovaná) poloha', 'Standardy první pomoci ČČK a ERC'),
  ('Jaké jsou typické příznaky předávkování opioidy (např. heroin, fentanyl, morfin) a jaká je první pomoc?', 'Intoxikace a předávkování opioidy (Naloxon)', 'Toxikologie a neodkladná péče ve vězeňství VS ČR'),
  ('Jak správně postupovat při generalizovaném epileptickém záchvatu (tonicko-klonické křeče celého těla) vězněné osoby na cele?', 'Epileptický záchvat a křečové stavy', 'První pomoc při neurologických urgentních stavech'),
  ('Jak se aplikuje autoinjektor s adrenalinem (EpiPen / Emerade) při rozvoji anafylaktického šoku (otok hrdla, dušení, pokles tlaku)?', 'Anafylaktický šok (těžká alergická reakce)', 'Doporučené postupy České společnosti alergologie a klinické imunologie'),
  ('Co znamená mezinárodní diagnostický test FAST pro rychlé rozpoznání cévní mozkové příhody (mrtvice)?', 'Cévní mozková příhoda (CMP) a test FAST', 'Národní doporučený postup pro iktovou péči v ČR'),
  ('Jaký je správný postup první pomoci u dospělého člověka při těžké neprůchodnosti dýchacích cest cizím tělesem (nemůže mluvit, kašlat ani dýchat, drží se za krk)?', 'Dusící se osoba (Obstrukce dýchacích cest)', 'ERC Guidelines – Management of Foreign Body Airway Obstruction (FBAO)'),
  ('Jaký je postup při poranění příslušníka VS ČR o použitou injekční jehlu nalezenou při bezpečnostní prohlídce na cele (riziko HIV, HBV, HCV)?', 'Infekční rizika a profylaxe personálu', 'Metodický pokyn Hlavního hygienika ČR a zdravotnické služby VS ČR'),
  ('Jak se správně ošetřuje hluboká krvácející rána v místech, kde nelze použít turniket (např. tříslo, podpaží, krk)?', 'Tlakový obvaz a packing rány', 'TCCC Guidelines – Junctional Bleeding Management'),
  ('Jaké jsou zásady manipulace s osobou s podezřením na poranění páteře (např. po pádu z výšky nebo autonehodě)?', 'Poranění páteře a manipulace', 'Traumatologie páteře a urgentní medicína'),
  ('Jak se poskytuje první pomoc při těžké hypoglykémii u diabetika (zmatenost, třes, pocení, agresivita až bezvědomí)?', 'Hypoglykemické kóma vs. Hyperglykémie', 'Diabetologie v akutní medicíně – ČLS JEP'),
  ('Jaké jsou typické varovné signály akutního infarktu myokardu (srdeční příhody)?', 'Akutní infarkt myokardu', 'Kardiologie pro záchranáře – Česká kardiologická společnost'),
  ('Jaká je správná první pomoc u silně podchlazeného vězně nalezeného v nevytápěném prostoru věznice (tělesná teplota <32 °C)?', 'Hypotermie a omrzliny', 'Urgentní medicína – Hypotermie a chladová poranění'),
  ('Jak se poskytuje první pomoc při mechanickém zapíchnutí cizího tělesa (např. střepu či kovu) do oční koule?', 'Poranění oka', 'Oftalmologie a urgentní péče v traumatologii'),
  ('Jaké klíčové informace musí příslušník VS ČR sdělit operátorovi Zdravotnické záchranné služby (linka 155) při hlášení závažného úrazu ve věznici?', 'Aktivace Záchranného řetězce (155 vs 112)', 'Standardy operačního řízení ZZS ČR a směrnice VS ČR'),
  ('Co zahrnuje klasické pravidlo 5T jako souhrn protišokových opatření při rozvoji traumatického šoku?', 'Šok a protišoková opatření (5T)', 'Standardy první pomoci Českého červeného kříže'),
  ('Jak se projevuje anafylaktický šok a jaká je neodkladná první pomoc?', 'Akutní stavy', 'Doporučené postupy ERC (Evropská resuscitační rada)'),
  ('Jaká je správná první pomoc u popálenin 2. a 3. stupně?', 'Traumata', 'Doporučené postupy ČČK'),
  ('Lze použít taktické turniketové škrtidlo (CAT) k zástavě masivního krvácení na krku?', 'TCCC - Zástava krvácení', 'Mezinárodní taktický standard TCCC'),
  ('Kam a jak se správně aplikuje taktické škrtidlo (turniket typu CAT) při masivním tepenném krvácení na končetině?', 'Masivní končetinové krvácení', 'Standardy Tactical Combat Casualty Care (TCCC) a metodika VS ČR'),
  ('Jaká je správná struktura čísla jednacího (ČJ) v informačním systému ETŘ?', 'Elektronická spisová služba ETŘ', 'Pokyn GŘ č. 4/2016 o spisové službě'),
  ('Jaký je 1. nejdůležitější úkol zpracovatele bezprostředně při založení spisu v ETŘ a proč?', 'Elektronická spisová služba ETŘ', 'Příručka ETŘ – Založení spisu'),
  ('V jaké hierarchii je v systému ETŘ povoleno provádět změnu typu spisu?', 'Elektronická spisová služba ETŘ', 'Metodika ETŘ v kostce'),
  ('Jaká pravidla platí v ETŘ pro slučování spisů?', 'Elektronická spisová služba ETŘ', 'Metodika ETŘ v kostce'),
  ('Co v systému ETŘ znamená a k čemu slouží tzv. „Sběrný arch“?', 'Elektronická spisová služba ETŘ', 'Metodika ETŘ v kostce'),
  ('Jaký je postup při skartačním řízení v ETŘ a jak se zachází se skartačním znakem „V“?', 'Elektronická spisová služba ETŘ', 'Metodika ETŘ v kostce'),
  ('Kdo podle § 16 NGŘ č. 41/2024 může zpracovat záznam o kázeňském přestupku vězněné osoby a v jaké lhůtě?', 'Kázeňské řízení a záznam o KP', 'NGŘ č. 41/2024 § 16'),
  ('Jaké povinné náležitosti musí obsahovat část „Popis skutku“ v záznamu o kázeňském přestupku?', 'Kázeňské řízení a záznam o KP', 'NGŘ č. 41/2024 § 16'),
  ('Jakým způsobem se do záznamu o kázeňském přestupku zaznamenává vyjádření podezřelého odsouzeného?', 'Kázeňské řízení a záznam o KP', 'NGŘ č. 41/2024 § 16'),
  ('Jaká slova musí příslušník podle § 6 odst. 3 písm. b) zákona č. 555/1992 Sb. použít před výzvou k upuštění od protiprávního jednání?', 'Záznam o použití donucovacích prostředků', '§ 6 odst. 3 písm. b) z. č. 555/1992 Sb.'),
  ('Která pole a údaje jsou v části první Záznamu o použití DP (příloha k PGŘ č. 3/2024) povinná?', 'Záznam o použití donucovacích prostředků', 'Příloha k PGŘ č. 3/2024'),
  ('Kdo zpracovává a schvaluje druhou část Záznamu o použití donucovacího prostředku?', 'Záznam o použití donucovacích prostředků', 'Příloha k PGŘ č. 3/2024'),
  ('Jaké tři evidenční stavy osob ve výkonu vazby, trestu a zabezpečovací detence rozeznává systém VIS?', 'Vězeňský informační systém VIS', 'Metodika VIS a evidence VS ČR'),
  ('Jaká jsou pravidla pro telefonické lustrace o vězněných osobách z centrální evidence VS ČR?', 'Vězeňský informační systém VIS', 'Metodika VIS – Lustrace'),
  ('Komu lze dle § 23a zákona č. 555/1992 Sb. poskytnout informaci o umístění vězněné osoby bez jejího souhlasu?', 'Vězeňský informační systém VIS', '§ 23a zákona č. 555/1992 Sb.'),
  ('Jaké je jedno ze základních stylistických pravidel pro psaní úředních záznamů (SZ, ZKP, záznam o DP) příslušníkem VS ČR?', 'Zásady úředního stylu a písemností', 'Manuál pro předmět Vězeňská administrativa'),
  ('Podle jakého zákonného ustanovení a jakým způsobem se sepisuje Záznam o odnětí věci u vězněné osoby?', 'Záznam o odnětí věci', '§ 12 zákona č. 555/1992 Sb.'),
  ('Jaký postup ukládá NGŘ č. 24/2022 při zjištění nebo oznámení fyzického násilí a známek ponižujícího jednání mezi vězněnými osobami?', 'Fyzické násilí a nevhodné jednání', 'NGŘ č. 24/2022'),
  ('Jaké prvky tvoří kompletní podpisovou doložku příslušníka VS ČR v úředním záznamu?', 'Zásady úředního stylu a písemností', 'Manuál pro předmět Vězeňská administrativa'),
  ('Co stanoví metodika ETŘ ohledně políčka „ZAMKNOUT“ při editaci popisu spisu?', 'Elektronická spisová služba ETŘ', 'Příručka ETŘ – Založení spisu'),
  ('Kdo a do jaké lhůty zpracovává „Záznam o použití donucovacího prostředku“ po zákroku proti vězněné osobě?', 'Úřední písemnosti', '§ 20 odst. 1 zákona č. 555/1992 Sb. a Metodický list č. 5/2014'),
  ('Jaké jsou tři základní skartační znaky při vyřazování dokumentů z elektronické spisové služby (ETŘ)?', 'Spisová služba', 'Zákon č. 499/2004 Sb., o archivnictví a spisové službě'),
  ('Je dozorce oprávněn telefonicky sdělit rodinnému příslušníkovi informaci o tom, zda je konkrétní osoba ve výkonu vazby?', 'Práce ve VIS', 'Zákon o VS a JS, GDPR a interní předpisy pro práci s VIS'),
  ('Co v modulu evidence osob ve VIS znamená rozdíl mezi "kmenovým stavem" a "fyzickým stavem" věznice?', 'Vězeňský informační systém', 'Manuál k Vězeňskému informačnímu systému (VIS)'),
  ('Která z následujících formulací ve Služebním záznamu nejlépe odpovídá pravidlům objektivního a formálního úředního stylu?', 'Úřední písemnosti', 'Pravidla pro tvorbu úředních písemností VS ČR'),
  ('Jaké povinné identifikační a časové údaje musí obsahovat Služební záznam o mimořádné události sepsaný příslušníkem v systému ETŘ/VIS?', 'Elektronický trestní rejstřík a VIS', 'Spisový řád VS ČR a NGŘ o vedení administrativy v informačních systémech'),
  ('V jaké zákonné lhůtě od zjištění kázeňského přestupku odsouzeného musí být přestupek projednán a uložen kázeňský trest dle § 52 zákona o VTOS?', 'Kázeňské řízení a lhůty', '§ 52 odst. 3 zákona č. 169/1999 Sb., o výkonu trestu odnětí svobody')
       ) AS v(question, topic, source)
 WHERE lower(btrim(q.question)) = lower(btrim(v.question))
   AND (
         ((q.source IS NULL OR btrim(q.source) = '' OR q.source = 'Banka otázek Supabase') AND v.source IS NOT NULL)
      OR ((q.topic IS NULL OR btrim(q.topic) = '') AND v.topic IS NOT NULL)
       );

COMMIT;

-- ============================================================================
-- OVĚŘENÍ (spustit zvlášť, jen čte)
-- ============================================================================
-- Obě chybné otázky jsou pryč (čeká se 0):
--   SELECT count(*) FROM public.quiz_questions
--    WHERE question LIKE '%zastavovací pás (§ 17)%'
--       OR question LIKE 'Jak přesně zní zákonná výzva%';
--
-- Kolik otázek je stále bez pramene (čeká se 0, nebo jen otázky přidané
-- lektorem v aplikaci):
--   SELECT count(*) FROM public.quiz_questions
--    WHERE source IS NULL OR btrim(source) = '' OR source = 'Banka otázek Supabase';
